version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.13-alpine
  entrypoint: ["sh"]
  working_dir: /parcel-plug
  volumes:
    - .:/parcel-plug:cached
    - ./node_modules:/parcel-plug/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    YARN_CACHE_FOLDER: /.yarn-cache
    NODE_ENV: development

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - "11001:27017"

  graphql:
    <<: *node
    working_dir: /parcel-plug/services/graphql
    entrypoint: ["/parcel-plug/node_modules/.bin/gulp"]
    environment:
      YARN_CACHE_FOLDER: /.yarn-cache
      NODE_ENV: development
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 11002
    depends_on:
      - mongodb
    ports:
      - "11002:80"

volumes:
  mongodb: {}
  yarn-cache: {}
